[tool.poetry]
name = "rr-inject"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
packages = [{include = "rr", from = "src"}]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"